SELECT *FROM Transactions WHERE Amount > 4000;
SELECT *FROM Transactions ORDER BY tDate DESC;
SELECT *FROM Transactions WHERE TransactionType = 'Deposit' ORDER BY Amount DESC;
SELECT *FROM (SELECT * FROM Transactions ORDER BY tDate DESC) WHERE ROWNUM <= 5;
SELECT *FROM Transactions ORDER BY TransactionType ASC, Amount DESC;
SELECT *FROM Transactions WHERE Amount > 1000;
SELECT *FROM Transactions WHERE tDate BETWEEN TO_DATE('2023-01-01', 'YYYY-MM-DD') AND TO_DATE('2023-06-30', 'YYYY-MM-DD');
SELECT *FROM Transactions WHERE TransactionType IN ('Deposit', 'Withdrawal');
SELECT *FROM Customers WHERE Address IS NULL;
SELECT *FROM Customers ORDER BY Address ASC NULLS LAST;
SELECT *FROM Customers ORDER BY (CASE WHEN Address IS NULL THEN 1 ELSE 0 END), Address ASC;
SELECT *FROM Transactions ORDER BY TDate DESC FETCH FIRST 5 ROWS ONLY;
SELECT *FROM Customers WHERE Name LIKE 'J%';
SELECT *FROM customers WHERE LOWER(name) LIKE 'j%';
SELECT *FROM Customers WHERE Name NOT LIKE '%Smith';
SELECT *FROM Transactions WHERE (TransactionType = 'Deposit' AND Amount > 4000) OR (TransactionType = 'Withdrawal' AND Amount > 500);
SELECT *FROM Transactions WHERE TransactionType NOT IN ('Deposit', 'Withdrawal');
SELECT *, Amount * 1.05 AS AdjustedAmount FROM Transactions ORDER BY AdjustedAmount DESC;
SELECT *FROM Customers WHERE Name LIKE '%a%';
SELECT TransactionType,COUNT(*) AS TotalTransactions FROM Transactions GROUP BY TransactionType ORDER BY COUNT(*) DESC;
SELECT *FROM Customers WHERE Name NOT LIKE '%e%';
SELECT *FROM Accounts WHERE Balance >= 500 ORDER BY Balance DESC;
SELECT *FROM Customers ORDER BY AccountCreationDate FETCH FIRST 5 ROWS ONLY;
SELECT *FROM Transactions WHERE Amount BETWEEN 100 AND 1000 ORDER BY tDate;
SELECT *FROM Customers WHERE Name LIKE 'A%' ORDER BY Name;