select salary, (salary+500) as increased_salary from employees;
select salary, (salary-200) as substracted_salary from employees;
select salary, (salary*1.2) as multiplied_salary from employees;
select salary, (salary/2) as divided_salary from employees;

select * from employees where salary = 5000;
select * from employees where salary != 5000;
select * from employees where salary > 6000;
select * from employees where salary < 4000;
select * from employees where salary >= 3000;
select * from employees where salary <= 2500;
select * from employees where department_id = 50;
select * from employees where job_id = 'SA_REP';
select * from employees where HIRE_DATE > '01-JAN-03';
select * from employees where department_id = 60 and salary > 5000;
select * from employees where deparment_id = 60 and commission_pct > 0.2;
select * from employees where department_id != 90;
select * from employees where (department_id = 60 and salary > 5000) or department_id = 50;
select * from employees where commission_pct is not null;
select * from employees where commission_pct is  null;

select * from employees where department_id in(30,50,80);
select * from employees where department_id not in(30, 50, 80);
select * from employees where salary between 3000 and 7000;
select * from employees where salary not between 3000 and 7000;
select * from employees where hire_date between '01-JAN-05' and '31-DEC-10';
select * from employees where first_name like 'A%';
select * from employees where length(first_name) = 5;
select * from employees where last_name not like 'S%';
select * from employees where job_id like '%MAN%';
select * from employees where last_name like '%\_%' escape '\';
select * from employees where salary > 3000 and hire_date > '01-JAN-15';
select * from employees where department_id = 90 or salary < 2000;
select * from employees where department_id != 60 and salary > 4000;
select * from employees where commission_pct is NULL or commission_pct > 0.2;
select * from employees where salary between 3000 and 7000 or department_id = 90;
select * from employees where department_id = 50 and salary not between 4000 and 8000;
select * from employees where first_name like 'J%' and first_name like '%n';
select * from employees where length(job_id) = 5 and job_id like '_\A%';
select * from employees where last_name like 'C%' or last_name like 'D%' or last_name like 'E%' or last_name like 'F%';  
select * from employees where department_id in(10,20,30);
select * from employees where job_id not in('IT_PROG','SA_REP','AD_PRES');

select * from employees where hire_date between '01-JAN-10' and '31-DEC-15';
select * from employees where salary not between 5000 and 10000;
select * from employees where last_name like '%k%' and last_name like '%S';
select * from employees where first_name like 'A%' and first_name not like '%N%';
select * from employees where job_id like 'S%' and job_id like '%REP';
select * from employees where commission_pct is NULL and salary > 6000;
select * from employees where commission_pct is not Null and commission_pct > 0.1;